#!/usr/bin/env python3
"""Generate index.json + INDEX.md from standards/ frontmatter.

Self-gate (Constitution C10): a standard whose content changed but whose version did not
bump refuses to index. Hashes live in checks/.index-hashes.json (committed).

Usage: python3 checks/build-index.py [--check]
  --check  verify index.json is current without rewriting (used by lint/CI)
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from datetime import date
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
STANDARDS = ROOT / "standards"
HASHES = ROOT / "checks" / ".index-hashes.json"
INDEX_JSON = ROOT / "index.json"
INDEX_MD = ROOT / "INDEX.md"

FAMILY_NAMES = {
    "SEC": "Security", "TST": "Testing", "ARC": "Architecture", "STK": "Stacks",
    "INF": "Infrastructure", "OPS": "Operations", "DEV": "Process", "UX": "UI/UX",
    "DATA": "Data governance", "AI": "LLM concerns", "LEG": "Legal/commercial",
}

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


def parse_standard(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise ValueError(f"{path}: no frontmatter block")
    meta = yaml.safe_load(m.group(1))
    if not isinstance(meta, dict):
        raise ValueError(f"{path}: frontmatter is not a mapping")
    return meta, text


def content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    errors: list[str] = []
    entries: list[dict] = []
    new_hashes: dict[str, dict] = {}
    old_hashes = json.loads(HASHES.read_text()) if HASHES.exists() else {}

    for path in sorted(STANDARDS.rglob("*.md")):
        try:
            meta, text = parse_standard(path)
        except ValueError as exc:
            errors.append(str(exc))
            continue
        sid = meta.get("id", "")
        version = str(meta.get("version", ""))
        digest = content_hash(text)
        prior = old_hashes.get(sid)
        if prior and prior["hash"] != digest and prior["version"] == version:
            errors.append(
                f"{path.relative_to(ROOT)}: content changed but version still "
                f"{version} — bump `version` and add a Changelog entry (C10)"
            )
        new_hashes[sid] = {"version": version, "hash": digest}
        entries.append({
            "id": sid,
            "title": meta.get("title", ""),
            "family": meta.get("family", ""),
            "version": version,
            "status": meta.get("status", ""),
            "tiers": meta.get("tiers", {}),
            "stacks": meta.get("stacks", "all"),
            "triggers": meta.get("triggers", []),
            "requires": meta.get("requires", []),
            "verification_layers": sorted({
                v.get("layer", "?") for v in (meta.get("verification") or [])
            }),
            "last_review": str(meta.get("last_review", "")),
            "path": str(path.relative_to(ROOT)),
            "tokens_est": len(text) // 4,
        })

    dupes = {e["id"] for e in entries if sum(x["id"] == e["id"] for x in entries) > 1}
    for d in sorted(dupes):
        errors.append(f"duplicate standard id: {d}")

    if errors:
        print("build-index: REFUSED\n" + "\n".join(f"  ✗ {e}" for e in errors))
        return 1

    index = {
        "schema": 1,
        "generated": date.today().isoformat(),
        "constitution": ["constitution/CONSTITUTION.md", "constitution/tiers.md"],
        "standards": entries,
    }
    payload = json.dumps(index, indent=2, sort_keys=False) + "\n"

    if check_only:
        if not INDEX_JSON.exists():
            print("build-index --check: index.json missing")
            return 1
        current = json.loads(INDEX_JSON.read_text())
        current["generated"] = index["generated"]  # date alone is not staleness
        if current != index:
            print("build-index --check: index.json is stale — run checks/build-index.py")
            return 1
        print(f"build-index --check: current ({len(entries)} standards)")
        return 0

    INDEX_JSON.write_text(payload, encoding="utf-8")
    HASHES.write_text(json.dumps(new_hashes, indent=2, sort_keys=True) + "\n")

    lines = [
        "# Standards Index",
        "",
        f"Generated by `checks/build-index.py` — do not edit. {len(entries)} standards.",
        "",
    ]
    for fam in FAMILY_NAMES:
        fam_entries = [e for e in entries if e["family"] == fam]
        if not fam_entries:
            continue
        lines += [f"## {fam} — {FAMILY_NAMES[fam]} ({len(fam_entries)})", ""]
        lines.append("| ID | Title | Version | Status | T1 | T2 | T3 | T4 |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for e in sorted(fam_entries, key=lambda x: x["id"]):
            t = e["tiers"]
            lines.append(
                f"| [{e['id']}]({e['path']}) | {e['title']} | {e['version']} "
                f"| {e['status']} | {t.get('T1', '?')} | {t.get('T2', '?')} "
                f"| {t.get('T3', '?')} | {t.get('T4', '?')} |"
            )
        lines.append("")
    INDEX_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"build-index: wrote index.json + INDEX.md ({len(entries)} standards)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
